# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import shared_storage_pb2 as shared__storage__pb2


class ModelAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.latest_model = channel.unary_unary(
                '/ModelAgent/latest_model',
                request_serializer=shared__storage__pb2.Empty.SerializeToString,
                response_deserializer=shared__storage__pb2.ModelInfo.FromString,
                )
        self.update_current_generated_model = channel.unary_unary(
                '/ModelAgent/update_current_generated_model',
                request_serializer=shared__storage__pb2.ModelInfo.SerializeToString,
                response_deserializer=shared__storage__pb2.Empty.FromString,
                )


class ModelAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def latest_model(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update_current_generated_model(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'latest_model': grpc.unary_unary_rpc_method_handler(
                    servicer.latest_model,
                    request_deserializer=shared__storage__pb2.Empty.FromString,
                    response_serializer=shared__storage__pb2.ModelInfo.SerializeToString,
            ),
            'update_current_generated_model': grpc.unary_unary_rpc_method_handler(
                    servicer.update_current_generated_model,
                    request_deserializer=shared__storage__pb2.ModelInfo.FromString,
                    response_serializer=shared__storage__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ModelAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ModelAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def latest_model(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ModelAgent/latest_model',
            shared__storage__pb2.Empty.SerializeToString,
            shared__storage__pb2.ModelInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def update_current_generated_model(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ModelAgent/update_current_generated_model',
            shared__storage__pb2.ModelInfo.SerializeToString,
            shared__storage__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
