# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: training_runtime.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='training_runtime.proto',
  package='tensorflow.muprover',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16training_runtime.proto\x12\x13tensorflow.muprover\x1a&tensorflow/core/framework/tensor.proto\"%\n\x10NumGamesResponse\x12\x11\n\tnum_games\x18\x01 \x01(\x05\"\xa1\x02\n\x0bGameHistory\x12*\n\x06states\x18\x01 \x03(\x0b\x32\x1a.tensorflow.muprover.State\x12\x0f\n\x07\x61\x63tions\x18\x02 \x03(\x05\x12\x0f\n\x07rewards\x18\x03 \x03(\x02\x12\x13\n\x0broot_values\x18\x04 \x03(\x02\x12)\n\x08policies\x18\x05 \x03(\x0b\x32\x17.tensorflow.TensorProto\x12@\n\x08metadata\x18\x06 \x03(\x0b\x32..tensorflow.muprover.GameHistory.MetadataEntry\x12\x11\n\treanalyse\x18\x07 \x01(\x08\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\"]\n\x05State\x12,\n\x0bobservation\x18\x01 \x01(\x0b\x32\x17.tensorflow.TensorProto\x12\x0f\n\x07to_play\x18\x02 \x01(\x05\x12\x15\n\rlegal_actions\x18\x03 \x03(\x05\x32\xcf\x01\n\x0fTrainingRuntime\x12X\n\x0bSaveHistory\x12 .tensorflow.muprover.GameHistory\x1a%.tensorflow.muprover.NumGamesResponse\"\x00\x12\x62\n\x13SaveMultipleHistory\x12 .tensorflow.muprover.GameHistory\x1a%.tensorflow.muprover.NumGamesResponse\"\x00(\x01\x62\x06proto3'
  ,
  dependencies=[tensorflow_dot_core_dot_framework_dot_tensor__pb2.DESCRIPTOR,])




_NUMGAMESRESPONSE = _descriptor.Descriptor(
  name='NumGamesResponse',
  full_name='tensorflow.muprover.NumGamesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_games', full_name='tensorflow.muprover.NumGamesResponse.num_games', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=124,
)


_GAMEHISTORY_METADATAENTRY = _descriptor.Descriptor(
  name='MetadataEntry',
  full_name='tensorflow.muprover.GameHistory.MetadataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tensorflow.muprover.GameHistory.MetadataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='tensorflow.muprover.GameHistory.MetadataEntry.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=416,
)

_GAMEHISTORY = _descriptor.Descriptor(
  name='GameHistory',
  full_name='tensorflow.muprover.GameHistory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='states', full_name='tensorflow.muprover.GameHistory.states', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='actions', full_name='tensorflow.muprover.GameHistory.actions', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rewards', full_name='tensorflow.muprover.GameHistory.rewards', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='root_values', full_name='tensorflow.muprover.GameHistory.root_values', index=3,
      number=4, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='policies', full_name='tensorflow.muprover.GameHistory.policies', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='tensorflow.muprover.GameHistory.metadata', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reanalyse', full_name='tensorflow.muprover.GameHistory.reanalyse', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GAMEHISTORY_METADATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=416,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='tensorflow.muprover.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='observation', full_name='tensorflow.muprover.State.observation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to_play', full_name='tensorflow.muprover.State.to_play', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='legal_actions', full_name='tensorflow.muprover.State.legal_actions', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=511,
)

_GAMEHISTORY_METADATAENTRY.containing_type = _GAMEHISTORY
_GAMEHISTORY.fields_by_name['states'].message_type = _STATE
_GAMEHISTORY.fields_by_name['policies'].message_type = tensorflow_dot_core_dot_framework_dot_tensor__pb2._TENSORPROTO
_GAMEHISTORY.fields_by_name['metadata'].message_type = _GAMEHISTORY_METADATAENTRY
_STATE.fields_by_name['observation'].message_type = tensorflow_dot_core_dot_framework_dot_tensor__pb2._TENSORPROTO
DESCRIPTOR.message_types_by_name['NumGamesResponse'] = _NUMGAMESRESPONSE
DESCRIPTOR.message_types_by_name['GameHistory'] = _GAMEHISTORY
DESCRIPTOR.message_types_by_name['State'] = _STATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NumGamesResponse = _reflection.GeneratedProtocolMessageType('NumGamesResponse', (_message.Message,), {
  'DESCRIPTOR' : _NUMGAMESRESPONSE,
  '__module__' : 'training_runtime_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.muprover.NumGamesResponse)
  })
_sym_db.RegisterMessage(NumGamesResponse)

GameHistory = _reflection.GeneratedProtocolMessageType('GameHistory', (_message.Message,), {

  'MetadataEntry' : _reflection.GeneratedProtocolMessageType('MetadataEntry', (_message.Message,), {
    'DESCRIPTOR' : _GAMEHISTORY_METADATAENTRY,
    '__module__' : 'training_runtime_pb2'
    # @@protoc_insertion_point(class_scope:tensorflow.muprover.GameHistory.MetadataEntry)
    })
  ,
  'DESCRIPTOR' : _GAMEHISTORY,
  '__module__' : 'training_runtime_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.muprover.GameHistory)
  })
_sym_db.RegisterMessage(GameHistory)
_sym_db.RegisterMessage(GameHistory.MetadataEntry)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'training_runtime_pb2'
  # @@protoc_insertion_point(class_scope:tensorflow.muprover.State)
  })
_sym_db.RegisterMessage(State)


_GAMEHISTORY_METADATAENTRY._options = None

_TRAININGRUNTIME = _descriptor.ServiceDescriptor(
  name='TrainingRuntime',
  full_name='tensorflow.muprover.TrainingRuntime',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=514,
  serialized_end=721,
  methods=[
  _descriptor.MethodDescriptor(
    name='SaveHistory',
    full_name='tensorflow.muprover.TrainingRuntime.SaveHistory',
    index=0,
    containing_service=None,
    input_type=_GAMEHISTORY,
    output_type=_NUMGAMESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SaveMultipleHistory',
    full_name='tensorflow.muprover.TrainingRuntime.SaveMultipleHistory',
    index=1,
    containing_service=None,
    input_type=_GAMEHISTORY,
    output_type=_NUMGAMESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRAININGRUNTIME)

DESCRIPTOR.services_by_name['TrainingRuntime'] = _TRAININGRUNTIME

# @@protoc_insertion_point(module_scope)
