# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import training_runtime_pb2 as training__runtime__pb2


class TrainingRuntimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveHistory = channel.unary_unary(
                '/tensorflow.muprover.TrainingRuntime/SaveHistory',
                request_serializer=training__runtime__pb2.GameHistory.SerializeToString,
                response_deserializer=training__runtime__pb2.NumGamesResponse.FromString,
                )
        self.SaveMultipleHistory = channel.stream_unary(
                '/tensorflow.muprover.TrainingRuntime/SaveMultipleHistory',
                request_serializer=training__runtime__pb2.GameHistory.SerializeToString,
                response_deserializer=training__runtime__pb2.NumGamesResponse.FromString,
                )


class TrainingRuntimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveMultipleHistory(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveHistory,
                    request_deserializer=training__runtime__pb2.GameHistory.FromString,
                    response_serializer=training__runtime__pb2.NumGamesResponse.SerializeToString,
            ),
            'SaveMultipleHistory': grpc.stream_unary_rpc_method_handler(
                    servicer.SaveMultipleHistory,
                    request_deserializer=training__runtime__pb2.GameHistory.FromString,
                    response_serializer=training__runtime__pb2.NumGamesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tensorflow.muprover.TrainingRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrainingRuntime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tensorflow.muprover.TrainingRuntime/SaveHistory',
            training__runtime__pb2.GameHistory.SerializeToString,
            training__runtime__pb2.NumGamesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveMultipleHistory(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/tensorflow.muprover.TrainingRuntime/SaveMultipleHistory',
            training__runtime__pb2.GameHistory.SerializeToString,
            training__runtime__pb2.NumGamesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
